displayName=Trouble Brewing Highlighter
author=GSVS UK ACM
description=Colour-coded Trouble Brewing routes, tools, ingredients and processing stations. This should assit players in finding what items are used where within Trouble Brewing. Over time I will add features and hopfully have it be more reactive then just static highlights but hope this helps massivly! Enjoy Gamers!
tags=trouble,brewing,minigame,highlight,helper,overlay
version=1.0.0
plugins=com.tbhelper.TroubleBrewingHighlighterPlugin
build=standard
