package com.tbhelper;

public enum ResourceType
{
    WATER,
    COLOURED_WATER,
    HOPPERS,
    BOILER_FUEL,
    BOILER_EMPTY,
    BOILER_UNLIT,
    BOILER_ACTIVE,
    BARK,
    PROCESSED_BARK,
    BAIT,
    GRUBS,
    FLOWERS,
    BITTERNUTS,
    BITTERNUTS_FINAL,
    ACTIVE_FIRE,
    PIPE_REPAIR,
    LUMBER_REPAIR,
    CONVEYOR,
    RUM,
    DAMAGE_REPAIR
}
